version: '3.1'

services:
  # abriella:
  #   build: .
  #   command: python3 ./main.py
  #   depends_on:
  #     - "postgres"
  #   env_file:
  #     - .env

  postgres:
    container_name: postgres_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: abriella_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  service-proxy:
      
